name: SplitSteal
version: 1.0
author: THELEGEND
website: mc-marketi.com
api-version: 1.13
main: tr.thelegend.splitsteal.Main
softdepend: [Vault]
commands:
    splitsteal:
        description: Main command
        aliases: [ss,ssteal]
permissions:
    splitsteal.main:
        description: Perm to main command
        default: op
    splitsteal.arena:
        description: Perm to check arenas
        default: op
    splitsteal.setup.create:
        description: Perm to create arenas
        default: op
    splitsteal.setup.setpos1:
        description: Perm to set the first position of an arena
        default: op
    splitsteal.setup.setpos2:
        description: Perm to set the second position of an arena
        default: op
    splitsteal.setup.setresult1:
        description: Perm to set the first result block of an arena
        default: op
    splitsteal.setup.setresult2:
        description: Perm to set the second result block of an arena
        default: op
    splitsteal.setup.delete:
        description: Perm to delete an arena
        default: op
    splitsteal.setup.setspawn:
        description: Perm to set spawn
        default: op
    splitsteal.setup.addbutton:
        description: Perm to add buttons
        default: op