name: SplitSteal
version: 1.0
author: THELEGEND
website: mc-marketi.com
api-version: 1.13
main: tr.thelegend.splitshare.Main
softdepend: [Vault]
commands:
    splitshare:
        description: Main command
        aliases: [ss,sshare]
permissions:
    splitshare.main:
        description: Perm to main command
        default: op
    splitshare.arena:
        description: Perm to check arenas
        default: op
    splitshare.setup.create:
        description: Perm to create arenas
        default: op
    splitshare.setup.setpos1:
        description: Perm to set the first position of an arena
        default: op
    splitshare.setup.setpos2:
        description: Perm to set the second position of an arena
        default: op
    splitshare.setup.setresult1:
        description: Perm to set the first result block of an arena
        default: op
    splitshare.setup.setresult2:
        description: Perm to set the second result block of an arena
        default: op
    splitshare.setup.delete:
        description: Perm to delete an arena
        default: op
    splitshare.setup.setspawn:
        description: Perm to set spawn
        default: op